issues with firestore
error : This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
[ng] Error: node_modules/@angular/fire/firestore/firestore.d.ts:8:8 - error TS1259: Module '"/Users/huguesfilscaparos/TaskManager/node_modules/firebase/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
[ng] 8 import firebase from 'firebase/app';

need to reinstall properly firebase